use_frameworks!

target 'GotandaMac' do
  pod 'Gotanda', :path => '../'
end

target 'Gotanda_Tests' do
  pod 'Gotanda', :path => '../' 
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = "3.0"
        end
    end
end
